/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.sql.Date;

public class App {

  public static void main(String[] args) {
    java.util.Scanner keyboard = new java.util.Scanner(System.in);
    
    System.out.print("번호: ");
    int no = keyboard.nextInt();
    
    keyboard.nextLine();
    
    System.out.print("수업명: ");
    String title = keyboard.nextLine();
    
    System.out.print("설명: ");
    String info = keyboard.nextLine();
    
    System.out.print("시작일: year-month-date ");
    Date startDate = Date.valueOf(keyboard.nextLine());
    
    System.out.print("종료일: year-month-date ");
    Date endDate = Date.valueOf(keyboard.nextLine());
    
    System.out.print("총수업시간: ");
    int totalHour = keyboard.nextInt();
    
    System.out.print("일수업시간: ");
    int dayHour = keyboard.nextInt();
    
    keyboard.close();
    System.out.println();

    
    System.out.printf("번호: %d\n", no);
    System.out.printf("수업명: %s\n", title);
    System.out.printf("설명: %s\n", info);
    System.out.printf("시작일: %s\n", startDate);
    System.out.printf("종료일: %s\n", endDate);
    System.out.printf("총수업시간: %d시간\n", totalHour);
    System.out.printf("일수업시간: %d시간\n", dayHour);
    
  }
}
