/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {

  public static void main(String[] args) {

    Scanner keyboard = new Scanner(System.in);

    final int length = 10;
    Lesson[] app = new Lesson[length];

    int i = 0;
    while (i < length) {

      Lesson main = new Lesson(); 

      System.out.print("명령> ");
      String input = keyboard.nextLine();
      if(input.equals("/lesson/add")) {

        System.out.print("번호? ");
        main.no = Integer.parseInt(keyboard.nextLine());

        System.out.print("수업명? ");
        main.title = keyboard.nextLine();

        System.out.print("수업내용 ? ");
        main.info = keyboard.nextLine();

        System.out.print("시작일 ? ");
        main.startDate = Date.valueOf(keyboard.nextLine());

        System.out.print("종료일 ? ");
        main.endDate = Date.valueOf(keyboard.nextLine());

        System.out.print("총수업일 ? ");
        main.totalHour = Integer.parseInt(keyboard.nextLine());

        System.out.print("일수업일? ");
        main.dayHour = Integer.parseInt(keyboard.nextLine());

        app[i++] = main; }
      //      i++;

      else if (input.equals("/lesson/list")) {
        int c = 0;
        while(c < i) {
          System.out.printf("%d, %-20s, %s ~ %s, %4d\n", app[c].no, app[c].title, app[c].startDate, app[c].endDate, app[c].totalHour);
          c++;
        }
      }
      else if(input.equals("quit")) { 
        System.out.println("안녕!");
        break;
      }
      else {
        System.out.println("실행할 수 없는 명령입니다.");
      }  
   keyboard.close();

    } // while end
  }// main end
}


